# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: gotcc CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.14
    - name: Test
      run: go test ./... -v
    - name: PrintMsg
      run: echo "--GOTCC--"
  codereport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cloc
      run: sudo apt install cloc
    - name: Generate report
      run: cloc . --include-lang="Go"
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
